name: drx
description: Run Dart tools and GitHub release binaries like npx/uvx.
version: 0.3.1
homepage: https://github.com/leehack/drx
repository: https://github.com/leehack/drx
issue_tracker: https://github.com/leehack/drx/issues

topics:
  - cli
  - tooling
  - automation
  - github

environment:
  sdk: ^3.10.8

dependencies:
  archive: ^4.0.7
  crypto: ^3.0.6
  path: ^1.9.0
  yaml: ^3.1.3

executables:
  drx: drx

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.0.0
  test: ^1.25.6
